# Pandas Basics

In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name":['shrey','anshu'],
    "marks":[80,96],
    "city":['belapur','bhubaneswar']
}

In [3]:
df= pd.DataFrame(dict1)

In [4]:
df

    name  marks         city
0  shrey     80      belapur
1  anshu     96  bhubaneswar

In [5]:
df.to_csv('friends.csv')

In [6]:
df.to_csv('friends_wo_index.csv', index=False)

In [7]:
df.head(1)

    name  marks     city
0  shrey     80  belapur

In [8]:
df.tail(1)

    name  marks         city
1  anshu     96  bhubaneswar

In [9]:
df.describe()

           marks
count   2.000000
mean   88.000000
std    11.313708
min    80.000000
25%    84.000000
50%    88.000000
75%    92.000000
max    96.000000

In [10]:
 train = pd.read_csv('shreytrain.csv')

In [11]:
train

   train no  speed         city
0     69420     80      belapur
1     11712     96  bhubaneswar

In [12]:
train['speed']

0    80
1    96
Name: speed, dtype: int64

In [13]:
train['speed'][0]

80

In [14]:
train.index = ['one','two']

In [15]:
train

     train no  speed         city
one     69420     80      belapur
two     11712     96  bhubaneswar

# Pandas Theory

Pandas is an open source data analysis lib written in py
1) power and speed of numpy to make data analysis and preprocessing
2) rich and highly robust data operations

Pandas has two types of DS:-

a) series - one dim array with indexes, it stores a single column or row of data in a dataframe.<br>
b) dataframe - tabular spreadsheet like struct representing rows each of which contains one or multiple columns.

> A one-dimensional array capable of holding any type of data - Series

> A two-dimensional data structure with columns of potentially different types iof data - Dataframe

# Jupyter Notebook

> Jupyter notebook is an open source web application that allows you to create and share docs that contain live code equations, viz and narrative text.

> The notebook has support of over 40 languages like Python, R, etc.

> Notebooks can be shared with others using Email, Dropbox, Github and Jupyter notebook viewer

> your code can produce rich interactive output: HTML, Images, videos, LaTeX and custome MIME types.

# Series and Dataframes

In [16]:
ser = pd.Series(np.random.rand)

In [17]:
ser

0    <built-in method rand of numpy.random.mtrand.R...
dtype: object

In [18]:
ser = pd.Series(np.random.rand(34))

In [19]:
ser

0     0.221491
1     0.160488
2     0.698695
3     0.048801
4     0.830011
5     0.213703
6     0.929225
7     0.586034
8     0.197275
9     0.280921
10    0.700598
11    0.509633
12    0.972208
13    0.711296
14    0.260930
15    0.668886
16    0.404200
17    0.141338
18    0.417496
19    0.851877
20    0.815374
21    0.859393
22    0.561168
23    0.505842
24    0.481336
25    0.342486
26    0.983752
27    0.182018
28    0.353492
29    0.570504
30    0.209252
31    0.994112
32    0.558857
33    0.784303
dtype: float64

In [20]:
type(ser)

pandas.core.series.Series

In [21]:
newdf = pd.DataFrame(np.random.rand(334,5), index=np.arange(334))

In [22]:
newdf.head()

          0         1         2         3         4
0  0.107439  0.051168  0.959815  0.741643  0.439324
1  0.482875  0.699305  0.111410  0.641424  0.972311
2  0.037083  0.637094  0.255494  0.701770  0.549154
3  0.428540  0.544097  0.934034  0.857904  0.456016
4  0.042016  0.498794  0.516691  0.437382  0.334836

In [23]:
newdf

            0         1         2         3         4
0    0.107439  0.051168  0.959815  0.741643  0.439324
1    0.482875  0.699305  0.111410  0.641424  0.972311
2    0.037083  0.637094  0.255494  0.701770  0.549154
3    0.428540  0.544097  0.934034  0.857904  0.456016
4    0.042016  0.498794  0.516691  0.437382  0.334836
..        ...       ...       ...       ...       ...
329  0.697865  0.417940  0.556931  0.218221  0.163950
330  0.628584  0.728245  0.101792  0.154110  0.603223
331  0.919675  0.748302  0.016201  0.234417  0.467573
332  0.976204  0.286567  0.368398  0.430623  0.168345
333  0.171576  0.681306  0.625322  0.333012  0.883549

[334 rows x 5 columns]

In [24]:
type(newdf)

pandas.core.frame.DataFrame

In [25]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.488306    0.493325    0.524212    0.486280    0.471617
std      0.284140    0.287098    0.282386    0.295980    0.286280
min      0.005519    0.012612    0.000265    0.000281    0.000283
25%      0.243427    0.237391    0.273541    0.216073    0.223172
50%      0.470287    0.510529    0.538375    0.487620    0.459678
75%      0.746807    0.753379    0.771707    0.727905    0.723667
max      0.992597    0.998507    0.998709    0.999969    0.998995

In [26]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [27]:
newdf [0][0] = "Shrey"

In [28]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [29]:
newdf.head

<bound method NDFrame.head of             0         1         2         3         4
0       Shrey  0.051168  0.959815  0.741643  0.439324
1    0.482875  0.699305  0.111410  0.641424  0.972311
2    0.037083  0.637094  0.255494  0.701770  0.549154
3     0.42854  0.544097  0.934034  0.857904  0.456016
4    0.042016  0.498794  0.516691  0.437382  0.334836
..        ...       ...       ...       ...       ...
329  0.697865  0.417940  0.556931  0.218221  0.163950
330  0.628584  0.728245  0.101792  0.154110  0.603223
331  0.919675  0.748302  0.016201  0.234417  0.467573
332  0.976204  0.286567  0.368398  0.430623  0.168345
333  0.171576  0.681306  0.625322  0.333012  0.883549

[334 rows x 5 columns]>

In [30]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int32', length=334)

In [31]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [32]:
newdf.to_numpy()

array([['Shrey', 0.051168112585557424, 0.9598145412589519,
        0.7416429555698426, 0.4393243155780242],
       [0.48287502822080397, 0.6993054611119814, 0.11140970791692228,
        0.6414237042269832, 0.9723109362985465],
       [0.0370829460508898, 0.637094346482884, 0.2554943552417588,
        0.701769573470153, 0.5491537467037807],
       ...,
       [0.9196752047079199, 0.7483022753829857, 0.016200838672068563,
        0.23441732337418486, 0.4675729024463038],
       [0.9762041277049933, 0.2865671335321758, 0.36839848629061855,
        0.43062268453114094, 0.1683454457899416],
       [0.17157571661457993, 0.6813059451392788, 0.6253221422172044,
        0.33301241390630276, 0.8835487314809675]], dtype=object)

In [33]:
newdf[0][0] = 0.3

In [34]:
newdf.head

<bound method NDFrame.head of             0         1         2         3         4
0         0.3  0.051168  0.959815  0.741643  0.439324
1    0.482875  0.699305  0.111410  0.641424  0.972311
2    0.037083  0.637094  0.255494  0.701770  0.549154
3     0.42854  0.544097  0.934034  0.857904  0.456016
4    0.042016  0.498794  0.516691  0.437382  0.334836
..        ...       ...       ...       ...       ...
329  0.697865  0.417940  0.556931  0.218221  0.163950
330  0.628584  0.728245  0.101792  0.154110  0.603223
331  0.919675  0.748302  0.016201  0.234417  0.467573
332  0.976204  0.286567  0.368398  0.430623  0.168345
333  0.171576  0.681306  0.625322  0.333012  0.883549

[334 rows x 5 columns]>

In [35]:
newdf.to_numpy()

array([[0.3, 0.051168112585557424, 0.9598145412589519,
        0.7416429555698426, 0.4393243155780242],
       [0.48287502822080397, 0.6993054611119814, 0.11140970791692228,
        0.6414237042269832, 0.9723109362985465],
       [0.0370829460508898, 0.637094346482884, 0.2554943552417588,
        0.701769573470153, 0.5491537467037807],
       ...,
       [0.9196752047079199, 0.7483022753829857, 0.016200838672068563,
        0.23441732337418486, 0.4675729024463038],
       [0.9762041277049933, 0.2865671335321758, 0.36839848629061855,
        0.43062268453114094, 0.1683454457899416],
       [0.17157571661457993, 0.6813059451392788, 0.6253221422172044,
        0.33301241390630276, 0.8835487314809675]], dtype=object)

In [36]:
newdf.T #Transpose

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.3,0.482875,0.037083,0.42854,0.042016,0.961651,0.188728,0.318344,0.442907,0.107821,...,0.306665,0.328986,0.404109,0.890554,0.300442,0.697865,0.628584,0.919675,0.976204,0.171576
1,0.051168,0.699305,0.637094,0.544097,0.498794,0.812752,0.588412,0.180309,0.127825,0.849074,...,0.897096,0.252303,0.621263,0.14474,0.361565,0.41794,0.728245,0.748302,0.286567,0.681306
2,0.959815,0.11141,0.255494,0.934034,0.516691,0.419877,0.205333,0.122434,0.339362,0.915885,...,0.710478,0.071353,0.551243,0.660826,0.225818,0.556931,0.101792,0.016201,0.368398,0.625322
3,0.741643,0.641424,0.70177,0.857904,0.437382,0.014662,0.374322,0.999969,0.13049,0.953224,...,0.663386,0.496859,0.641334,0.699055,0.959863,0.218221,0.15411,0.234417,0.430623,0.333012
4,0.439324,0.972311,0.549154,0.456016,0.334836,0.31988,0.675681,0.572253,0.749076,0.632874,...,0.482597,0.861729,0.852561,0.748898,0.192713,0.16395,0.603223,0.467573,0.168345,0.883549

In [37]:
newdf.sort_index(axis=0, ascending=False)

            0         1         2         3         4
333  0.171576  0.681306  0.625322  0.333012  0.883549
332  0.976204  0.286567  0.368398  0.430623  0.168345
331  0.919675  0.748302  0.016201  0.234417  0.467573
330  0.628584  0.728245  0.101792  0.154110  0.603223
329  0.697865  0.417940  0.556931  0.218221  0.163950
..        ...       ...       ...       ...       ...
4    0.042016  0.498794  0.516691  0.437382  0.334836
3     0.42854  0.544097  0.934034  0.857904  0.456016
2    0.037083  0.637094  0.255494  0.701770  0.549154
1    0.482875  0.699305  0.111410  0.641424  0.972311
0         0.3  0.051168  0.959815  0.741643  0.439324

[334 rows x 5 columns]

In [38]:
newdf.head()

          0         1         2         3         4
0       0.3  0.051168  0.959815  0.741643  0.439324
1  0.482875  0.699305  0.111410  0.641424  0.972311
2  0.037083  0.637094  0.255494  0.701770  0.549154
3   0.42854  0.544097  0.934034  0.857904  0.456016
4  0.042016  0.498794  0.516691  0.437382  0.334836

In [39]:
newdf[0]

0           0.3
1      0.482875
2      0.037083
3       0.42854
4      0.042016
         ...
329    0.697865
330    0.628584
331    0.919675
332    0.976204
333    0.171576
Name: 0, Length: 334, dtype: object

In [40]:
type(newdf[0])

pandas.core.series.Series

In [47]:
newdf2 = newdf #newdf2 is now a view of newdf...
#this means that any changes made to newdf2 will be reflected on newdf.
#pointer bhalia basically

In [44]:
#newdf3 = newdf[:] or newdf3 = newdf.copy() to make a copy

In [48]:
newdf3 = newdf.copy()

In [49]:
newdf.loc[0,0] = 654

In [50]:
newdf.head(2)

          0         1         2         3         4
0       654  0.051168  0.959815  0.741643  0.439324
1  0.482875  0.699305  0.111410  0.641424  0.972311

In [51]:
newdf.columns = list("ABCDE")

In [52]:
newdf

            A         B         C         D         E
0         654  0.051168  0.959815  0.741643  0.439324
1    0.482875  0.699305  0.111410  0.641424  0.972311
2    0.037083  0.637094  0.255494  0.701770  0.549154
3     0.42854  0.544097  0.934034  0.857904  0.456016
4    0.042016  0.498794  0.516691  0.437382  0.334836
..        ...       ...       ...       ...       ...
329  0.697865  0.417940  0.556931  0.218221  0.163950
330  0.628584  0.728245  0.101792  0.154110  0.603223
331  0.919675  0.748302  0.016201  0.234417  0.467573
332  0.976204  0.286567  0.368398  0.430623  0.168345
333  0.171576  0.681306  0.625322  0.333012  0.883549

[334 rows x 5 columns]

In [53]:
newdf.loc[0,'A'] = 52343

In [54]:
newdf

            A         B         C         D         E
0       52343  0.051168  0.959815  0.741643  0.439324
1    0.482875  0.699305  0.111410  0.641424  0.972311
2    0.037083  0.637094  0.255494  0.701770  0.549154
3     0.42854  0.544097  0.934034  0.857904  0.456016
4    0.042016  0.498794  0.516691  0.437382  0.334836
..        ...       ...       ...       ...       ...
329  0.697865  0.417940  0.556931  0.218221  0.163950
330  0.628584  0.728245  0.101792  0.154110  0.603223
331  0.919675  0.748302  0.016201  0.234417  0.467573
332  0.976204  0.286567  0.368398  0.430623  0.168345
333  0.171576  0.681306  0.625322  0.333012  0.883549

[334 rows x 5 columns]

In [56]:
newdf.loc[[1,2],['C','D']]

          C         D
1  0.111410  0.641424
2  0.255494  0.701770

In [58]:
newdf.loc[:,['C','D']]

            C         D
0    0.959815  0.741643
1    0.111410  0.641424
2    0.255494  0.701770
3    0.934034  0.857904
4    0.516691  0.437382
..        ...       ...
329  0.556931  0.218221
330  0.101792  0.154110
331  0.016201  0.234417
332  0.368398  0.430623
333  0.625322  0.333012

[334 rows x 2 columns]

In [59]:
newdf.loc[[1,2],:]

          A         B         C         D         E
1  0.482875  0.699305  0.111410  0.641424  0.972311
2  0.037083  0.637094  0.255494  0.701770  0.549154